version: '3'
services:
  web:
    container_name: web
    restart: always
    build: .
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    networks:
    - frontend
networks:
  frontend:
    external: true
